[package]
name = "chat-webrtc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = {version ="4.5.7", features=["derive"]}
serde_json = "1.0.118"
tokio = {version="1.38.0", features=["full"]}
webrtc = "0.11.0"
